<a href="https://colab.research.google.com/github/np03cs4a240249-ctrl/portfolio-BishalBudha/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array((2,2))
print(arr1)

[2 2]


In [ ]:
import numpy as np
arr2=np.ones((4,2))
print(arr2)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
arr3=np.full((2,2),1)
print(arr3)

[[1 1]
 [1 1]]


In [ ]:
import numpy as np
arr4=np.array([[1,2],[3,4]])
arr_zero=np.zeros_like(arr4)
print(arr_zero)

[[0 0]
 [0 0]]


In [ ]:
import numpy as np
arr5=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_one=np.ones_like(arr5)
print(arr_one)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
new_list=[1,2,3,4]
arr6=np.array(new_list)
print(arr6)

[1 2 3 4]


In [ ]:
import numpy as np
arr7=np.arange(10,49)
print(arr7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
import numpy as np
arr8=np.arange(0,9)
reshape_array=np.reshape(arr8,(3,3))
print(reshape_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
identity_matrix=np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
arr1=np.random.random(30)
mean=arr1.mean()
print(arr1)
print(mean)

[0.11859193 0.78987082 0.57275757 0.91152526 0.22222566 0.19844382
 0.66807379 0.7354228  0.31971275 0.78734466 0.84880714 0.27694505
 0.38376005 0.02733494 0.45375929 0.62815037 0.17846899 0.31481587
 0.11384293 0.01070185 0.91514049 0.52280662 0.27574122 0.00298772
 0.51862175 0.79583232 0.23071051 0.71347146 0.89233253 0.26164488]
0.45632816792058933


In [ ]:
import numpy as np
arr1=np.random.random((10,10))
mini=np.min(arr1)
maxi=np.max(arr1)
print(arr1)
print(mini)
print(maxi)

[[0.47267597 0.00753645 0.82393118 0.84433575 0.22628193 0.78889209
  0.64534679 0.96463745 0.93362009 0.47863729]
 [0.14341913 0.10859578 0.89434143 0.29761965 0.91733116 0.14439502
  0.3214589  0.66910255 0.00303261 0.66702857]
 [0.57750147 0.03109423 0.84602736 0.7216609  0.58085787 0.36812691
  0.42818804 0.13815477 0.19477721 0.62639635]
 [0.69641931 0.05507438 0.91423935 0.98335007 0.62626511 0.59410939
  0.1786978  0.81048904 0.96454139 0.9750939 ]
 [0.12761052 0.84646968 0.97512523 0.54387532 0.03286794 0.4300965
  0.00174059 0.86568207 0.73820203 0.84604929]
 [0.53410039 0.11688042 0.13320994 0.73544679 0.78126752 0.06985232
  0.23232509 0.83206773 0.11353898 0.21968312]
 [0.93904433 0.56574042 0.31700946 0.23110271 0.3513275  0.23237741
  0.81058179 0.77707666 0.0677824  0.22334282]
 [0.31155161 0.18835999 0.28596455 0.31372135 0.35636686 0.26107258
  0.04285267 0.16482143 0.67184389 0.39679949]
 [0.22652422 0.52543419 0.41233462 0.7552785  0.98580321 0.41694905
  0.74844761 

In [ ]:
import numpy as np
arr1=np.zeros((4,6))
arr1[:, 4] = 1
print(arr1)

[[0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
print(arr[::-1])

[0 4 0 0 2 1]


In [ ]:
import numpy as np
arr=np.ones((4,4))
arr[1:-1,1:-1]=0
print (arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
arr=np.ones((8,8))
arr[1::2, ::2]=0
arr[::2, 1::2]=0
print (arr)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
addition1=np.add(x,y)
addition2=np.add(v,w)
print("Addition of x and y=",addition1)
print("Addition of v and w=",addition1)

Addition of x and y= [[ 6  8]
 [10 13]]
Addition of v and w= [[ 6  8]
 [10 13]]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
subtract1=np.subtract(x,y)
subtract2=np.subtract(v,w)
print("Subtract of x and y=",subtract1)
print("Subtract of v and w=",subtract2)

Subtract of x and y= [[-4 -4]
 [-4 -3]]
Subtract of v and w= [-2 -2]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
v = np.array([9,10])
multiply1=np.multiply(x,2)
multiply2=np.multiply(v,3)
print("Multiplying x with 2=",multiply1)
print("Multiplying v with 3=", multiply2)

Multiplying x with 2= [[ 2  4]
 [ 6 10]]
Multiplying v with 3= [27 30]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
square1=np.square(x)
square2=np.square(y)
square3=np.square(v)
square4=np.square(w)
print("Square of x=",square1)
print("Square of y=",square2)
print("Square of v=",square3)
print("Square of w=",square4)

Square of x= [[ 1  4]
 [ 9 25]]
Square of y= [[25 36]
 [49 64]]
Square of v= [ 81 100]
Square of w= [121 144]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
Product1=np.dot(v,w)
Product2=np.dot(x,v)
Product3=np.dot(x,y)
print("Dot product of v and w=",Product1)
print("Dot product of x and v=",Product2)
print("Dot product of x and y=",Product3)

Dot product of v and w= 219
Dot product of x and v= [29 77]
Dot product of x and y= [[19 22]
 [50 58]]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
hstacked=np.hstack((x,y))
vstacked=np.vstack((v,w))
print("Concatenate along row=",hstacked)
print("Concatenate along row=",vstacked)

Concatenate along row= [[1 2 5 6]
 [3 5 7 8]]
Concatenate along row= [[ 9 10]
 [11 12]]


In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

Inverse_of_A=np.linalg.inv(A)
Identity=np.dot(A,Inverse_of_A)
print(Identity)
print("\n")
AB=np.dot(A,B)
BA=np.dot(B,A)
print("A * B =", AB)
print("B * A =", BA)
print("\n")
transpose_AB=np.transpose(AB)
transpose_A=np.transpose(A)
transpose_B=np.transpose(B)
A_transpose_B_transpose=np.dot(transpose_B,transpose_A)
print("Transpose of AB=",transpose_AB)
print("Transpose of A and B=",A_transpose_B_transpose)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


A * B = [[23 13]
 [51 29]]
B * A = [[36 44]
 [13 16]]


Transpose of AB= [[23 51]
 [13 29]]
Transpose of A and B= [[23 51]
 [13 29]]


In [ ]:
import numpy as np
A=np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B=np.array([-1,-3,9])
A_Inverse=np.linalg.inv(A)
X=np.dot(A_Inverse,B)
print(X)
print("\n")
X2=np.linalg.solve(A,B)
print(X2)

[ 2.  1. -2.]


[ 2.  1. -2.]
